### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: timeout

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/node-red-contrib-uhppoted#2]
From console log while investigating https://github.com/uhppoted/node-red-contrib-uhppoted/issues/1:

```
5 Dec 13:35:25 - [warn] [set-door-control:set-door-control] uhppoted::Error: invalid door control undefined
      (node:947) UnhandledPromiseRejectionWarning: Error: timeout
         at Timeout._onTimeout (/Users/tonyseebregts/Development/uhppote/uhppoted/node-red-contrib-uhppoted/nodes/uhppoted.js:437:41)
         at listOnTimeout (internal/timers.js:551:17)
         at processTimers (internal/timers.js:494:7)
      (Use `node --trace-warnings ...` to show where the warning was created)
      (node:947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
      (node:947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by twystd** [comment]
The _timeout_ timer in `uhppoted::receiveAny` was not being cancelled on exiting `uhppoted::get/set` due to an error.

Added a `cancel` function to the returned `Promise` and wrapped the invocation in a `try..finally`
